const Prompts = [
    // EASY
    {
      q: "Who is this soccer player?",
      h1: "From Portugal",
      h2: "Has 5 Ballon d'Or awards",
      h3: "Manchester United; Real Madrid",
      fullName: "Cristiano Ronaldo",
      a: ["Ronaldo", 'ronaldo', 'RONALDO', 'cristiano ronaldo', 'Cristiano Ronaldo'],
      img: "ronaldo",
      difficulty: "easy",
    },
    {
      q: "Who is this soccer player?",
      h1: "From Argentina",
      h2: "Has 7 Ballon d'Or awards",
      h3: "Barcelona; PSG",
      fullName: "Lionel Messi",
      a: ["Messi", 'MESSI', 'messi', 'Lionel Messi, lionel messi'],
      img: 'messi',
      difficulty: "easy",
    },
    {
        q: "Who is this soccer player?",
        h1: "From Brazil",
        h2: "UEFA Champions League Winner",
        h3: "Olymic Gold Medalist",
        fullName: "Neymar Jr.",
        a: ['Neymar', 'neymar'],
        img: 'neymar',
        difficulty: "easy",
      },
    //MEDIUM
    {
        q: "Who is this soccer player?",
        h1: "From Egypt",
        h2: "Has 1 Ballon d'Or awards",
        h3: "2x Premier League Winner",
        fullName: "Mohamed Salah",
        a: ['Salah', 'salah', 'Mohamed Salah', 'mohamed salah'],
        img: 'salah',
        difficulty: "medium",
    },
    {
        q: "Who is this soccer player?",
        h1: "From Spain",
        h2: "World Cup Winner",
        h3: "4x UEFA Champions League Winner",
        fullName: "Sergio Ramos",
        a: ['Ramos', 'ramos', 'Sergio Ramos', 'sergio ramos'],
        img: 'ramos',
        difficulty: "medium",
    },
    {
        q: "Who is this soccer player?",
        h1: "From Ecuador",
        h2: "Chelsea",
        h3: "Youngest player to debut for Ecuador in a World Cup qualifier",
        fullName: "Moisés Caicedo",
        a: ['Caicedo', 'caicedo', 'Moises Caicedo', 'moises caicedo'],
        img: 'caicedo',
        difficulty: "medium",
    },
    {
        q: "Who is this soccer player?",
        h1: "From Argentina",
        h2: "5x Premier League Champion",
        h3: "Manchester City's all-time top scorer",
        fullName: "Sergio Agüero",
        a: ['Aguero', 'aguero', 'Sergio Aguero', 'sergio aguero', 'sergio agüero', 'Sergio Agüero', 'agüero', 'Agüero'],
        img: 'aguero',
        difficulty: "medium",
    },
    // HARD
    {
        q: "Who is this soccer player?",
        h1: "From Peru",
        h2: "Top Scorer in the 2018 World Cup Qualifiers (South America)",
        h3: "Copa Libertadores Winner",
        fullName: "Paolo Guerrero",
        a: ['Guerrero', 'guerrero', 'Paolo Guerrero', 'paolo guerrero'],
        img: 'guerrero',
        difficulty: "hard",
    },
    {
        q: "Who is this soccer player?",
        h1: "From Ecuador",
        h2: "Top Scorer in the 2014 World Cup for Ecuador",
        h3: "Copa Sudamerica Winner",
        fullName: "Enner Valencia",
        a: ['valencia' , 'Valencia', 'Enner Valencia', 'enner valencia'],
        img: 'valencia',
        difficulty: "hard",
    },
    {
        q: "Who is this soccer player?",
        h1: "From Italy",
        h2: "2x UEFA Champion League Winner",
        h3: "World Cup Winner",
        fullName: "Andrea Pirlo",
        a: ['pirlo' , 'Pirlo', 'Andrea Pirlo', 'andrea pirlo'],
        img: 'pirlo',
        difficulty: "hard",
    },
  ];
  
  export default Prompts;