const Prompts = [
    // EASY
    {
      q: "Who is this soccer player?",
      h1: "From Portugal",
      h2: "Has 5 Ballon d'Or awards",
      h3: "Manchester United; Real Madrid",
      a: "Cristiano Ronaldo",
      img: "ronaldo",
      difficulty: "easy",
    },
    {
      q: "Who is this soccer player?",
      h1: "From Argentina",
      h2: "Has 7 Ballon d'Or awards",
      h3: "Barcelona; PSG",
      a: "Lionel Messi",
      img: 'messi',
      difficulty: "easy",
    },
    {
        q: "Who is this soccer player?",
        h1: "From Brazil",
        h2: "UEFA Champions League Winner",
        h3: "Olymic Gold Medalist",
        a: "Neymar Jr.",
        img: 'neymar',
        difficulty: "easy",
      },
    //MEDIUM
    {
        q: "Who is this soccer player?",
        h1: "From Egypt",
        h2: "Has 1 Ballon d'Or awards",
        h3: "2x Premier League Winner",
        a: "Mohamed Salah",
        img: 'salah',
        difficulty: "medium",
    },
    {
        q: "Who is this soccer player?",
        h1: "From Spain",
        h2: "World Cup Winner",
        h3: "4x UEFA Champions League Winner",
        a: "Sergio Ramos",
        img: 'ramos',
        difficulty: "medium",
    },
    {
        q: "Who is this soccer player?",
        h1: "From Ecuador",
        h2: "Chelsea",
        h3: "Youngest player to debut for Ecuador in a World Cup qualifier",
        a: "Moisés Caicedo",
        img: 'caicedo',
        difficulty: "medium",
    },
    {
        q: "Who is this soccer player?",
        h1: "From Argentina",
        h2: "5x Premier League Champion",
        h3: "Manchester City's all-time top scorer",
        a: "Sergio Agüero",
        img: 'aguero',
        difficulty: "medium",
    },
    // HARD
    {
        q: "Who is this soccer player?",
        h1: "From Peru",
        h2: "Top Scorer in the 2018 World Cup Qualifiers (South America)",
        h3: "Copa Libertadores Winner",
        a: "Paolo Guerrero",
        img: 'guerrero',
        difficulty: "hard",
    },
    {
        q: "Who is this soccer player?",
        h1: "From Ecuador",
        h2: "Top Scorer in the 2014 World Cup for Ecuador",
        h3: "Copa Sudamerica Winner",
        a: "Enner Valencia",
        img: 'valencia',
        difficulty: "hard",
    },
    {
        q: "Who is this soccer player?",
        h1: "From Italy",
        h2: "2x UEFA Champion League Winner",
        h3: "World Cup Winner",
        a: "Andrea Pirlo",
        img: 'pirlo',
        difficulty: "hard",
    },
  ];
  
  export default Prompts;